[package]
name = "xen"
version = "0.1.0" # Per SemVer

[addresses]
xen = "9ed9f3d3bac4e121f17b6ce602714c0c34bfd3b9ab8ec5760252050648a53e48"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
# rev = "01108a2345b87d539d54a67b32db55193f9ace40"
rev = "main"
# rev = "563e2abff8fa997aec81abe48772af8a20731f76"
