[package]
name = "xen"
version = "0.1.0" # Per SemVer

[addresses]
xen = "0x393a63f47da7a757a252cb44fbab2afe602efe9d88e8ae84aac7db4949a9beb0"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework"
# rev = "01108a2345b87d539d54a67b32db55193f9ace40"
rev = "main"